# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 68e5e1c85772384b09dbf5dbc50a1a4349d739cef6bf865b452403f718047fd26ce4f2c923e82fdeae30934b28429f7965951d8d8c56e7c164695a4b000ae5e5

test:
  secret_key_base: 739a49e06e6118b699696edf6fa63c551acb1fa73b593b759a7db5e2ecc3308e106e33ca5482e8a4cfa78bebb9d615817752e521a10c43de113f0c5fd366b46d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
